/*
 * Custom status screen for the Sofle's two 128x32 SSD1306 panels.
 *
 * This is ZMK's built-in screen (zmk/app/src/display/status_screen.c) plus
 * one thing: the right half gets the SD wordmark.
 *
 * That asymmetry is not decoration, it is the only option. Every widget worth
 * showing is gated on being the CENTRAL side of the split --
 * zmk/app/src/display/widgets/Kconfig makes LAYER, OUTPUT and WPM
 * `depends on !ZMK_SPLIT || ZMK_SPLIT_ROLE_CENTRAL`, because a peripheral
 * never runs the keymap and therefore cannot know the layer, the active
 * output, or how fast you are typing. A peripheral is allowed a battery
 * readout and a connection icon, and that is the entire list. So the right
 * half has 128x32 pixels and nothing to say with them.
 *
 *   LEFT  (central)      RIGHT (peripheral)
 *   +--------------+     +--------------+
 *   |OUT      BATT |     | SD      BATT |
 *   |layer     wpm |     | __      conn |
 *   +--------------+     +--------------+
 */

#include <zephyr/kernel.h>

#include <zephyr/logging/log.h>
LOG_MODULE_DECLARE(zmk, CONFIG_ZMK_LOG_LEVEL);

#include <zmk/display/status_screen.h>
#include <zmk/display/widgets/battery_status.h>
#include <zmk/display/widgets/layer_status.h>
#include <zmk/display/widgets/output_status.h>
#include <zmk/display/widgets/peripheral_status.h>
#include <zmk/display/widgets/wpm_status.h>

/* CONFIG_ZMK_SPLIT_ROLE_CENTRAL is only meaningful on a split, and this
 * shield is always one -- but spell it out so the file is honest about what
 * it assumes. */
#define SD_IS_PERIPHERAL (IS_ENABLED(CONFIG_ZMK_SPLIT) && !IS_ENABLED(CONFIG_ZMK_SPLIT_ROLE_CENTRAL))

#if SD_IS_PERIPHERAL
/* Generated by scripts/gen-logo into display/sd_logo.c, and only linked into
 * the peripheral build (see CMakeLists.txt). */
LV_IMG_DECLARE(sd_logo);
#endif

#if IS_ENABLED(CONFIG_ZMK_WIDGET_BATTERY_STATUS)
static struct zmk_widget_battery_status battery_status_widget;
#endif

#if IS_ENABLED(CONFIG_ZMK_WIDGET_OUTPUT_STATUS)
static struct zmk_widget_output_status output_status_widget;
#endif

#if IS_ENABLED(CONFIG_ZMK_WIDGET_PERIPHERAL_STATUS)
static struct zmk_widget_peripheral_status peripheral_status_widget;
#endif

#if IS_ENABLED(CONFIG_ZMK_WIDGET_LAYER_STATUS)
static struct zmk_widget_layer_status layer_status_widget;
#endif

#if IS_ENABLED(CONFIG_ZMK_WIDGET_WPM_STATUS)
static struct zmk_widget_wpm_status wpm_status_widget;
#endif

lv_obj_t *zmk_display_status_screen(void) {
    lv_obj_t *screen = lv_obj_create(NULL);

#if SD_IS_PERIPHERAL
    /* 68 of the 128 columns, full height, hard left -- the remaining ~60
     * carry the battery and the connection icon without overlapping it.
     * lv_img_create + lv_image_set_src is the pairing ZMK's own nice_view
     * peripheral widget uses on this LVGL; the v8 and v9 spellings coexist
     * and mixing them is upstream's choice, not a slip. */
    lv_obj_t *logo = lv_img_create(screen);
    lv_image_set_src(logo, &sd_logo);
    lv_obj_align(logo, LV_ALIGN_LEFT_MID, 0, 0);
#endif

#if IS_ENABLED(CONFIG_ZMK_WIDGET_BATTERY_STATUS)
    zmk_widget_battery_status_init(&battery_status_widget, screen);
    lv_obj_align(zmk_widget_battery_status_obj(&battery_status_widget), LV_ALIGN_TOP_RIGHT, 0, 0);
#endif

#if IS_ENABLED(CONFIG_ZMK_WIDGET_OUTPUT_STATUS)
    zmk_widget_output_status_init(&output_status_widget, screen);
    lv_obj_align(zmk_widget_output_status_obj(&output_status_widget), LV_ALIGN_TOP_LEFT, 0, 0);
#endif

#if IS_ENABLED(CONFIG_ZMK_WIDGET_PERIPHERAL_STATUS)
    /* Bottom right, not top left as in the built-in screen: the logo owns the
     * left half here. */
    zmk_widget_peripheral_status_init(&peripheral_status_widget, screen);
    lv_obj_align(zmk_widget_peripheral_status_obj(&peripheral_status_widget), LV_ALIGN_BOTTOM_RIGHT,
                 0, 0);
#endif

#if IS_ENABLED(CONFIG_ZMK_WIDGET_LAYER_STATUS)
    zmk_widget_layer_status_init(&layer_status_widget, screen);
    lv_obj_set_style_text_font(zmk_widget_layer_status_obj(&layer_status_widget),
                               lv_theme_get_font_small(screen), LV_PART_MAIN);
    lv_obj_align(zmk_widget_layer_status_obj(&layer_status_widget), LV_ALIGN_BOTTOM_LEFT, 0, 0);
#endif

#if IS_ENABLED(CONFIG_ZMK_WIDGET_WPM_STATUS)
    zmk_widget_wpm_status_init(&wpm_status_widget, screen);
    lv_obj_align(zmk_widget_wpm_status_obj(&wpm_status_widget), LV_ALIGN_BOTTOM_RIGHT, 0, 0);
#endif

    return screen;
}
